[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sender = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
force = true
optimizer = true
auto_detect_remappings = false
optimizer_runs = 999999
evm_version = "london"
bytecode_hash = "ipfs"
extra_output_files = ["metadata"]

[rpc_endpoints]
sepolia = "https://rpc.ankr.com/eth_sepolia"
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
